### ISSUE TITLE
Testing UC2 with Ryu/Core/Ryu

### ISSUE THREAD

**Issue by ElisaRojas** [fp7-netide/Usecases#1] opened 2016-06-10 08:10 UTC
Hi,

I'm writing this issue on behalf of @Juanma-Sanchez , who wrote the email to @doriguzzi in the first place. He was testing UC2 in the Ryu/Core/Ryu combination (as the UC2 is now implemented in Ryu) and he's having the following problem:

UC2 uses LLDP to obtain the topology and then use it for optimal routing. However, when he uses NetIDE, he's found out that the topology module (called "switches" in Ryu) is not receiving the proper information. LLDP messages go down to the network and then up to the backend (we checked that with Wireshark), but the problem is that they are not being forwarded to the switches modules, but only to the UC2 module (called IITS_NetManager in the screenshot below). Moreover, he found out that the switches modules is recognized by the core as another module (see below).

![netide-module-list](https://cloud.githubusercontent.com/assets/2779496/15957954/b81d7592-2ef2-11e6-8fb2-8342882227fd.PNG)

Juanma's has been checking through the ModuleIDs of a Wireshark capture (we can send it if you need it), and he could only find the ID 719 that represents our aplication (UC2).

It seems that the problem is that the switches module isn't receiving any LLDP although it is recognized by the core. 

He later on tried to add the switches module to the composition file, but it was unsuccessful. I don't recall now the problem, @Juanma-Sanchez , could you remind us?

We are assigning @doriguzzi to the issue, as the author of the Ryu backend, but if Arne could check the issue as well, as he know about the behaviour of the core (and maybe explain if we could add a composition file for it), it would be great.

Any help would be really appreaciated!
Best,

P.S: We might stop using LLDP (and hardcode the topology) if it has no solution, but ideally, this being solved would be nice.

**Comment by Juanma-Sanchez** [comment] 2016-06-13 08:28
Hi,

Sorry for the delay. This is the error I get when I try  to add the switches module to the composition file as if it was another application:
![image](https://cloud.githubusercontent.com/assets/16320771/16001259/60b5daa4-3151-11e6-8bc7-bc261c43b1d1.png)

As Elisa said, any help would be appreaciated.
Thanks.

**Comment by doriguzzi** [comment] 2016-06-23 10:10
Could you please post the command you use to run the ryu backend so that I can reproduce the error?

Thanks

**Comment by Juanma-Sanchez** [comment] 2016-06-23 10:18
Yes, it's:
ryu-manager --ofp-tcp-listen-port 7733 --observe-links ~/NetIDE/Engine-mixed/ryu-backend/ryu-backend.py IITS_NetManager.py

The IITS_NetManager.py file is in Usecases/Usecase2/ryu/Application/
Thanks

**Comment by doriguzzi** [comment] 2016-06-29 13:46
Hi Elisa, Juan,

please find in the ryu-backend-lldp branch a prototype of the ryu-backend that sends the lldp messages to all the modules running atop.
I tested it and it should work. However, do not hesitate to contact me in case of errors/problems.

--rob

**Comment by Juanma-Sanchez** [comment] 2016-07-01 16:30
Hello @doriguzzi, 
With the new backend the switches module is receiving (at least some of) the lldps, but the routing table doesn't seem to update correctly:
![image](https://cloud.githubusercontent.com/assets/16320771/16527909/c614dd3e-3fb9-11e6-87ec-9d55cf925968.png)
Any idea why could this be?

If it may be helpful, I used a new vagrant machine (in which i disabled Ipv6 in the grub and installed python-ipaddr), with the attached composition specification and called the backend with th command:
_ryu-manager --ofp-tcp-listen-port 7733 --observe-links ~/NetIDE/Engine-mixed/ryu-backend-lldp/ryu-backend.py IITS_NetManager.py_

Thanks in advance.

[CompositionSpecification.zip](https://github.com/fp7-netide/Usecases/files/343843/CompositionSpecification.zip)

**Comment by doriguzzi** [comment] 2016-07-01 19:17
What does it happen with the "official" backend (i.e. the one without the patch for LLDP messages)?. Do you have the same percentage of dropped packets?

**Comment by doriguzzi** [comment] 2016-07-01 20:00
If I try to reproduce the same environment using the mininet script provided in the Usecase2/ryu/Topology folder, I get an error because IPCONFIG.dat does not exist.

**Comment by ElisaRojas** [comment] 2016-07-02 11:19
Thank you @doriguzzi , AFAIK with the "official" backend all pings are dropped (because no learning is done at all via LLDP). With this new backend some learning is done (and that is why some pings work), but apparently not all... @Juanma-Sanchez tried to print the different LLDP arriving, but could not see the reason.

As for the *.dat, I think it has been ignored when uploading due to .gitignore. Let's see if @Juanma-Sanchez can upload it on Monday (just delete the *.dat in .gitignore and try to upload it again).

**Comment by ElisaRojas** [comment] 2016-07-02 11:45
Hi again @doriguzzi , I've just uploaded the IPCONFIG.dat file. Apparently, the *.dat file was the one from the Pyretic project and @Juanma-Sanchez did not have it either, so he was executing the scenario ignoring that error. In any case, I've uploaded the file anyway.

Therefore, you can either execute it without the *dat or with it. @Juanma-Sanchez has been testing everything without it so far and ignoring the error, if you want to follow the same scenario.

**Comment by doriguzzi** [comment] 2016-07-02 13:30
As a first step I'm running mininet with command "sudo python UC2_IITSystem.py" and the application with just Ryu, no Network Engine. However, pingall does not work at all and after a while I get the following error:

![image](https://cloud.githubusercontent.com/assets/1794129/16540575/ce6e78ea-4069-11e6-911e-ffb9aa20f7a4.png)

I'm using Ryu version 3.27.

**Comment by Juanma-Sanchez** [comment] 2016-07-02 16:22
The only thing that comes to mind is that you may be missing the _"--observe-links"_ option when running the application (it's necessary for the ryu topology api). That wouldn't explain the error, but I don't have any other plausible explanation.

**Comment by ElisaRojas** [comment] 2016-07-06 12:13
Hi @doriguzzi , please let us know if you tried with the _"--observe-links"_ as well. If you still have errors, maybe we can organize a quick telco to debug the issue together :)
Thanks for your help!

**Comment by doriguzzi** [comment] 2016-07-21 13:43
When I run the IITS_NetManager.py application on top of the Engine, the ryu-backend detects two applications: IITS_NetManager.py and switches.py (which, I guess, is activated by  "--observe-links" ). I see both of them receiving the same LLDP packets that are also received by the backend. Could you please tell me how you detect the anomaly?

**Comment by Juanma-Sanchez** [comment] 2016-07-22 11:34
Hello @doriguzzi , there has been a problem. I detected the anomaly indirectly using the routing table that gets printed when the application starts (the entries that were set all to ones meant the switches module didn't receive the lldp messages).

I was going to include screenshots, but I have updated the java core to its latest version and now the ryu-backend-lldp doesn't complete the handshake (the regular one does), although the core seems to be receiving the backend messages. Do you know what could have happened?

**Comment by Juanma-Sanchez** [comment] 2016-07-26 09:38
Hello,

The application is working properly with the python core, but when I use the java core the lldp messages don't reach neither the application or the switches module.

**Comment by schwabe** [comment] 2016-07-26 10:27
Can you provide a log of the core?

**Comment by Juanma-Sanchez** [comment] 2016-07-26 10:53
There is the following recurring error:
![image](https://cloud.githubusercontent.com/assets/16320771/17135391/dc5df90c-532f-11e6-8171-6b4d01a622ba.png)

[karaf-log.zip](https://github.com/fp7-netide/Usecases/files/383649/karaf-log.zip)

**Comment by schwabe** [comment] 2016-07-26 11:43
Compsition empty for packet means exactly that. The core has no backend to forward that packet to so it is dropping it. How does your composition file look like?

**Comment by Juanma-Sanchez** [comment] 2016-07-26 11:47
It looks like this:

![image](https://cloud.githubusercontent.com/assets/16320771/17136774/abcb63f8-5337-11e6-9858-baa3bd27a85d.png)

I'm also using the ryu-backend from the ryu-backend-lldp branch, not the master one.

**Comment by schwabe** [comment] 2016-07-26 11:49
Should that composition xml be in the https://github.com/fp7-netide/Usecases/tree/master/Usecase2 folder?

That compsition.xml looks not even valid. I would be suprised if netide:loadcomposition accepts that composition file.

**Comment by schwabe** [comment] 2016-07-26 11:57
next time you might want to put your code inside ``` instead of posting an image.

Your Composition is indeed empty. There is no   `<Composition>` in your xml at all. See the example specification files in the core.

**Comment by Juanma-Sanchez** [comment] 2016-07-26 12:07
Ok, now it's working, thank you very much. I have added the new composition specification to the repository.

**Comment by schwabe** [comment] 2016-07-26 12:09
I am closing this now then.

**Closed as completed by schwabe** 2016-07-26 12:09 UTC

**Comment by ElisaRojas** [comment] 2016-07-26 12:25
Hi, one final question to @doriguzzi . Should we merge the new backend into the master branch?
Thanks everybody for your help! :)
